homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt
serial:
  port: /dev/ttyACM0
  adapter: auto
frontend:
  port: 8080
advanced:
  log_level: error
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
devices:
  '0x70ac08fffe65a18c':
    friendly_name: '0x70ac08fffe65a18c'
  '0x00158d607fe00e5a':
    friendly_name: '0x00158d607fe00e5a'
availability:
  active:
    timeout: 10
  passive:
    timeout: 1500
groups:
  '666':
    friendly_name: pisces
    devices: []
