name: IOT deploy actions
on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

  build:
    needs: setup
    runs-on: self-hosted
    env:
      DESTINATION_PATH: /home/pi/CIANDT_CD2103/code-files/
    steps:
      - name: Copy files to destination
        run: whoami

      - name: Copy files to destination
        run: cp -R ${{ github.workspace }}/* $DESTINATION_PATH

      - name: Start the docker container
        run: |
          cd $DESTINATION_PATH
          docker-compose up -d

      - name: Display job status
        run: echo "This job's status is ${{ job.status }}."
