name: Deploy IOT

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Copy Files
        run: cp -r ${{ github.workspace }}/* ~/code-files/
