name: IOT deploy actions
on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

  build:
    needs: setup
    runs-on: self-hosted
    env:
      DESTINATION_PATH: /home/pi/CIANDT_CD2103/code-files/
    steps:
      - name: Check if DESTINATION_PATH exists or create
        run: |
          if [ ! -d "$DESTINATION_PATH" ]; then
            mkdir -p $DESTINATION_PATH
          fi

      - name: Sync files to destination
        run: sudo rsync -av --delete ${{ github.workspace }}/ $DESTINATION_PATH

      - name: Check Docker status and start/restart container
        run: |
          if [ "$(docker inspect -f '{{.State.Running}}' middleware-phpswoole 2>/dev/null)" == "true" ]; then
            docker restart middleware-phpswoole
          else
            cd $DESTINATION_PATH
            docker network create zigbee2mqtt_default
            docker-compose up -d
          fi

      - name: Display job status
        run: echo "This job's status is ${{ job.status }}."
