name: IOT deploy actions
run-name: ${{ github.actor }} publish this version.
on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

  build:
    needs: setup
    runs-on: self-hosted
    steps:
      - name: Copy files to destination
        run: cp -R ${{ github.workspace }}/* /home/pi/CIANDT_CD2103/code-files/

      - name: Display job status
        run: echo "This job's status is ${{ job.status }}."